import logging
import asyncio
from typing import Dict, Any
from .risk_manager import RiskManager
from .data_logger import DataLogger

class ExecutionEngine:
    """
    ExecutionEngine handles placing dual-sided (YES/NO) orders across the Polymarket CLOB.
    It supports 'paper' and 'live' modes.
    """

    def __init__(self, mode: str, risk_manager: RiskManager, data_logger: DataLogger):
        """
        Args:
            mode (str): 'paper' or 'live'.
            risk_manager (RiskManager): Injected RiskManager instance.
            data_logger (DataLogger): Injected DataLogger instance.
        """
        self.mode = mode.lower()
        self.risk_manager = risk_manager
        self.data_logger = data_logger
        self.logger = logging.getLogger(self.__class__.__name__)

    async def execute_arbitrage(self, signal: Dict[str, Any]) -> bool:
        """
        Evaluates the signal against risk parameters and executes the orders.
        
        Args:
            signal (Dict[str, Any]): The trading signal generated by ArbitrageDetector.
            
        Returns:
            bool: True if execution was completed successfully, False otherwise.
        """
        market_id = signal.get("market_id")
        
        # 1. Ask RiskManager if we are allowed to take this trade
        risk_evaluation = self.risk_manager.evaluate_trade(signal)
        if not risk_evaluation.get("allowed"):
            self.logger.warning(f"Trade rejected by RiskManager: {risk_evaluation.get('reason')}")
            return False

        position_size = risk_evaluation.get("recommended_size_usd", 10.0)

        self.logger.info(f"Executing trade for {market_id} | Mode: {self.mode.upper()} | Size: ${position_size:.2f}")

        # 2. Simulate API delays (mock network latency)
        await asyncio.sleep(0.1) # 100ms realistic mock delay
        
        if self.mode == "live":
            # TODO: Implement actual CLOB API POST actions via 'polymarket-py'
            # try:
            #     order_yes = api.create_order(side='buy', token_id=YES_TOKEN, price=..., size=...)
            #     order_no  = api.create_order(side='buy', token_id=NO_TOKEN,  price=..., size=...)
            # except Exception as e:
            #     ...
            pass
        elif self.mode == "paper":
            # In paper mode we assume absolute fills.
            pass
        else:
            self.logger.error(f"Unknown mode '{self.mode}'")
            return False

        # 3. Log the successful execution
        estimated_profit = position_size * signal.get("estimated_profit_per_share", 0)
        self.data_logger.log_trade({
            "market_id": market_id,
            "mode": self.mode,
            "size_usd": position_size,
            "spread": signal.get("spread", 0.0),
            "estimated_profit": estimated_profit,
            "status": "WIN" if self.mode == "paper" else "FILLED" # Simplified for paper mode
        })
        
        self.risk_manager.register_position(market_id)
        self.logger.info(f"Executed pair on {market_id} | Est. Profit: +${estimated_profit:.2f}")

        return True
